project:
  type: website
  output-dir: docs
  render:
    - index.qmd

lang: en-GB

bibliography:
  - "Statistical classes.bib"
  - "references/p-value-fallacy.bib"
  - "references/multiple-tests.bib"
